### ISSUE TITLE
found strings may be formatted as a heading

### ISSUE THREAD

**Issue by Presskopp** [Clorith/wordpress-string-locator#148]
If the source contains a H2 (or similar), the string may not be shown correctly, but formatted as H2 etc.

for example if a file contains:
`<h2><?php _e('Nope', 'memberpress'); ?></h2>`

it will be shown as:

![image (6)](https://user-images.githubusercontent.com/18373563/122203917-d34b1580-ce9e-11eb-8cf8-6208b72b077d.png)

looks like the regex in class-string-locator.php ~L.1365 needs to be adjusted to prevent this.

**Comment by Presskopp** [comment]
turns out this is not happening when 3rd party plugins are disabled so there must be some interference

**Comment by Clorith** [comment]
If you have an overview of which plugins you might have enabled causing this strange behavior, please feel free to send it over at such a time and I'd be happy to look into why this might be happening, and if it's something that can be prevented on this plugins side.

Until then, I'm going to mark this as closed as it doesn't appear to be a problem with the plugin it self, based on your feedback.
