### ISSUE TITLE
Feature Request: Case sensitive search

### ISSUE THREAD

**Issue by Presskopp** [Clorith/wordpress-string-locator#149]
Please :-)

**Comment by Clorith** [comment]
Hiya,

You should already be able to do case sensitive searches by utilizing the regex option, and not adding the `i` (case insensitive) flag.

For example, a search of `/Dolly/` with regex enabled for the Hello Dolly plugin provides the following result screen:
![](https://user-images.githubusercontent.com/468735/155866314-fc56c560-c0dd-4f38-9d6a-fb2e8e87fec6.png)

Where as the same search with the `i` flag, `/Dolly/i`, gives the following set of results (note the inclusion of for example `function hello_dolly_get_lyric()` in this result set, which is lowercase, despite the uppercase used in the search):
![](https://user-images.githubusercontent.com/468735/155866338-14de4639-0c50-4c22-89dc-9febeb040131.png)

Going to close this out, as case-sensitive searching is something I'd put within the realm of "more advanced use", and the Regex search is there for just such cases :)
