### ISSUE TITLE
Bug with Managed Hosting

### ISSUE THREAD

**Issue by igorradovanov** [Clorith/wordpress-string-locator#39]
Hello,

I would like to point a bug with the latest version on Managed Hosting plans where the plugin is not visible in the Tools menu nor the plugin renders the options page due to incorrect capability used: **update_core**. 

Most Managed Hosting providers have disabled updates, they are done by the system automatically so this capability is not present. 

Instead, I would like to advise **manage_options** capability to be used instead which works beautifully. I've tested this behavior on GoDaddy hosting but could be the same situation on other Managed Hosting providers.

Thank you.

**Comment by Clorith** [comment]
Thank you for the report!

This has been resolved with cdada143d376be06bdf84ed9142d3ca7484d7496, although it uses `install_plugins` over `manage_options`, to keep it as locked down as possible. I don't want to accidentally give access to finding credentials or similar.
